PROGRAM            = "program"
BLOCK              = "block"
VAR_SECTION        = "variable_section"
VAR_DECL           = "variable_declaration"
SUBROUTINE_SECTION = "subroutine_section"
PROCEDURE          = "procedure_declaration"
FUNCTION           = "function_declaration"
SUBROUTINE_BLOCK   = "subroutine_block"
COMMAND_SEQ        = "command_sequence"
PARAMETERS         = "parameters"
PARAMETER          = "parameter"

ASSIGN             = "assignment"
PROC_CALL          = "procedure_call"
IF                 = "if_statement"
WHILE              = "while_loop"
READ               = "read_statement"
WRITE              = "write_statement"

BINARY_OP          = "binary_operation"
UNARY_OP           = "unary_operation"

VAR                = "variable_reference"
BOOL               = "boolean_literal"
FUNC_CALL          = "function_call"
# ID                 = "identifier"
NUM                = "numeric_literal"
