PROGRAM            = "program"
BLOCK              = "block"
VAR_SECTION        = "var_section"
VAR_DECL           = "var_decl"
SUBROUTINE_SECTION = "subroutine_section"
PROCEDURE          = "procedure"
FUNCTION           = "function"
SUBROUTINE_BLOCK   = "subroutine_block"
BEGIN_END          = "begin_end"
PARAMETERS         = "parameters"
PARAMETER          = "parameter"

ASSIGN             = "assign"
PROC_CALL          = "proc_call"
IF                 = "if"
WHILE              = "while"
READ               = "read"
WRITE              = "write"

BINARY_OP          = "binary_op"
UNARY_OP           = "unary_op"

VAR                = "var"
BOOL               = "bool"
FUNC_CALL          = "func_call"
ID                 = "id"
NUM                = "num"